export const TASKS_LOADING = "TASKS_LOADING";
export const ADD_TASKS = "ADD_TASKS";
export const TASKS_FAILED = "TASKS_FAILED";

export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";

export const LABELS_LOADING = "LABELS_LOADING";
export const ADD_LABELS = "ADD_LABELS";
export const LABELS_FAILED = "LABELS_FAILED";

export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const ADD_PROJECTS = "ADD_PROJECTS";
export const PROJECTS_FAILED = "PROJECTS_FAILED";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
