export const TASKS_LOADING = "TASKS_LOADING";
export const ADD_TASKS = "ADD_TASKS";
export const TASKS_FAILED = "TASKS_FAILED";
export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS";
export const POST_TASK_FAILED = "POST_TASK_FAILED";
export const PUT_TASK_SUCCESS = "PUT_TASK_SUCCESS";
export const PUT_TASK_FAILED = "PUT_TASK_FAILED";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILED = "DELETE_TASK_FAILED";

export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const POST_NEW_CMT_SUCCESS = "POST_NEW_CMT_SUCCESS";

export const LABELS_LOADING = "LABELS_LOADING";
export const ADD_LABELS = "ADD_LABELS";
export const LABELS_FAILED = "LABELS_FAILED";

export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const ADD_PROJECTS = "ADD_PROJECTS";
export const PROJECTS_FAILED = "PROJECTS_FAILED";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const POPULATE_TASK_LOADING = "POPULATE_TASK_LOADING";
export const POPULATE_TASK_COMPLETE = "POPULATE_TASK_COMPLETE";
