export const COMMENTS = [
  {
    id: 0,
    taskId: 2,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 1,
    taskId: 3,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 2,
    taskId: 1,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 3,
    taskId: 2,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 4,
    taskId: 3,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 5,
    taskId: 1,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 6,
    taskId: 2,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 7,
    taskId: 3,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 8,
    taskId: 1,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 9,
    taskId: 2,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
  {
    id: 10,
    taskId: 3,
    text: "Imagine all the eatables, living in conFusion!",
    date: "2012-10-16",
    time: "15:30",
  },
 
];
