export const tasks = [
  {
    id: 1,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment"],
    progress: 25,
    priority: 1,
    label: "label",
    project: "Project",
    remindMe: false,
  },
  {
    id: 2,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 50,
    priority: 3,
    label: "label",
    project: "Project",
    remindMe: true,
  },
  {
    id: 3,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 50,
    priority: 3,
    label: "label",
    project: "Project",
    remindMe: true,
  },
  {
    id: 4,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 50,
    priority: 3,
    label: "label",
    project: "Project",
    remindMe: true,
  },
  {
    id: 5,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project",
    remindMe: true,
  },
  {
    id: 6,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project",
    remindMe: true,
  },
  {
    id: 7,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project",
    remindMe: true,
  },
  {
    id: 8,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project",
    remindMe: true,
  },
  {
    id: 9,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project",
    remindMe: true,
  },
];
