export const TASKS = [
  {
    id: 1,
    title: "My task",
    dueDate: "2019-02-01",
    progress: 10,
    priority: 1,
    label: 1,
    project: 1,
    remindMe: false,
  },
  {
    id: 2,
    title: "Title",
    dueDate: "2021-09-01",
    progress: 50,
    priority: 3,
    label: 2,
    project: 2,
    remindMe: true,
  },
  {
    id: 3,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 50,
    priority: 3,
    label: 3,
    project: 3,
    remindMe: true,
  },
  {
    id: 4,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 50,
    priority: 3,
    label: 1,
    project: 3,
    remindMe: true,
  },
  {
    id: 5,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 2,
    project: 1,
    remindMe: true,
  },
  {
    id: 6,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 3,
    project: 2,
    remindMe: true,
  },
  {
    id: 7,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 2,
    project: 1,
    remindMe: true,
  },
  {
    id: 8,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 3,
    project: 1,
    remindMe: true,
  },
  {
    id: 9,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 1,
    project: 2,
    remindMe: true,
  },
  {
    id: 10,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 3,
    project: 3,
    remindMe: true,
  },
  {
    id: 11,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 1,
    project: 3,
    remindMe: true,
  },
  {
    id: 12,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 3,
    project: 2,
    remindMe: true,
  },
  {
    id: 13,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 2,
    project: 3,
    remindMe: true,
  },
  {
    id: 14,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 3,
    project: 1,
    remindMe: true,
  },
  {
    id: 15,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 1,
    project: 3,
    remindMe: true,
  },
  {
    id: 16,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 2,
    project: 1,
    remindMe: true,
  },
  {
    id: 17,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 2,
    project: 2,
    remindMe: true,
  },
  {
    id: 18,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 3,
    project: 1,
    remindMe: true,
  },
  {
    id: 19,
    title: "Title",
    dueDate: "2019-02-01",
    progress: 0,
    priority: 3,
    label: 3,
    project: 1,
    remindMe: true,
  },
];
