export const tasks = [
  {
    id: 1,
    title: "My task",
    dueDate: "1/2/2019",
    comments: [
      "This task is important !",
      "Second comment",
      "Third comment",
      "Fourth comment",
      "Fifth comment",
      "Sixth comment",
    ],
    progress: 10,
    priority: 1,
    label: "label",
    project: "Project 2",
    remindMe: false,
  },
  {
    id: 2,
    title: "Title",
    dueDate: "1/9/2021",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 50,
    priority: 3,
    label: "label",
    project: "Project 2",
    remindMe: true,
  },
  {
    id: 3,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 50,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 4,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 50,
    priority: 3,
    label: "label",
    project: "Project 1",
    remindMe: true,
  },
  {
    id: 5,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 2",
    remindMe: true,
  },
  {
    id: 6,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 7,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 1",
    remindMe: true,
  },
  {
    id: 8,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 2",
    remindMe: true,
  },
  {
    id: 9,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 10,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 11,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 12,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 13,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 14,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 15,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 16,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 17,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 18,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
  {
    id: 19,
    title: "Title",
    dueDate: "1/2/2019",
    comments: ["This task is important !", "Second comment", "Third Comment"],
    progress: 0,
    priority: 3,
    label: "label",
    project: "Project 3",
    remindMe: true,
  },
];
